# Generated by Django 2.1.7 on 2019-04-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ITClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('fname', models.CharField(max_length=120)),
                ('mname', models.CharField(max_length=120)),
                ('lname', models.CharField(max_length=120)),
                ('pan', models.CharField(max_length=10)),
                ('dob', models.DateTimeField()),
                ('eFlPass', models.CharField(max_length=120)),
                ('address1', models.CharField(max_length=120)),
                ('address2', models.CharField(max_length=120)),
                ('address3', models.CharField(max_length=120)),
                ('address4', models.CharField(max_length=120)),
                ('pincode', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('business_name', models.CharField(max_length=120)),
                ('assesee_type', models.CharField(max_length=60)),
                ('adhar', models.CharField(max_length=12)),
                ('match', models.CharField(max_length=120)),
                ('activeUser', models.CharField(blank=True, default=None, max_length=120, null=True)),
            ],
        ),
    ]
