# Generated by Django 2.1.7 on 2019-05-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itclient',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='itclient',
            name='pincode',
            field=models.CharField(max_length=20),
        ),
    ]
