# Generated by Django 2.1.7 on 2019-05-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0003_auto_20190502_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='itclient',
            name='fullname',
            field=models.CharField(default='<django.db.models.fields.CharField> <django.db.models.fields.CharField> <django.db.models.fields.CharField>', max_length=120),
        ),
    ]
